inspiration = ["The only limit to our realization of tomorrow will be our doubts of today",
"Don’t be afraid to give up the good for the great",
"The secret of getting ahead is getting started",
"The only impossible journey is the one you never begin",
"The best way to get started is to quit talking and begin doing",
"When you know what you want, and want it bad enough, you’ll find a way to get it",
"Never let the fear of striking out keep you from playing the game",
"If you genuinely want something, don’t wait for it"
"The most difficult thing is the decision to act; the rest is merely tenacity",
"You don’t have to be great to start, but you have to start to be great",
"You miss 100% of the shots you don’t take",
"Everything you’ve ever wanted is on the other side of fear",
"I believe that the only courage anybody ever needs is the courage to follow your dreams",
"Whatever the mind of man can conceive and believe, it can achieve",
"Whether you think you can or think you can’t, you’re right",
"Magic is believing in yourself; if you can do that, you can make anything happen",
"Believe you can, and you’re halfway there",
"There are no limits to what you can accomplish, except the limits you place on your own thinking",
"All our dreams will come true if we have the courage to pursue them",
"Too many of us are not living our dreams because we are living our fears",
"I have learned over the years that when one’s mind is made up, this diminishes fear",
"Believe you can, and you’re halfway there",
"In this moment, I am euphoric. Not because of any phony god's blessing. But because, I am enlightened by my intelligence",
"All our dreams will come true, if we have the courage to pursue them",
"The secret of change is to focus all of your energy, not on fighting the old, but on building the new",
"A bad attitude is like a flat tire; if you don’t change it, you won’t go anywhere",
"The future belongs to those who believe in the beauty of their dreams",
"Dream big and dare to fail",
"Setting goals is the first step in turning the invisible into the visible",
"Imagine your life is perfect in every respect; what would it look like?",
"I think goals should never be easy; they should force you to work, even if they are uncomfortable at the time",
"People who are crazy enough to think they can change the world are the ones who do",
"Whatever the mind can conceive and believe, it can achieve",
"If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success",
"You are never too old to set another goal or to dream a new dream",
"Dreaming, after all, is a form of planning",
"Always bear in mind that your own resolution to success is more important than any other one thing",
"I find that the harder I work, the more luck I seem to have",
"I never dreamed about success; I worked for it",
"For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded",
"Success is walking from failure to failure with no loss of enthusiasm",
"I attribute my success to this: I never gave or took any excuse",
"Success usually comes to those who are too busy to be looking for it",
"Today’s accomplishments were yesterday’s impossibilities",
"If you look really closely, most overnight successes took a long time",
"When you want to succeed as bad as you want to breathe, then you’ll be successful",
"Things work out the best for those who make the best of how things work out",
"You suck",
"Success is a personal standard, reaching for the highest that is in us, becoming all we can be",
"The road to success and the road to failure are almost exactly the same",
"Success is not final; failure is not fatal: it is the courage to continue that counts",
"Our greatest glory is not in never falling, but in rising every time we fall",
"You will face many defeats in life, but never let yourself be defeated",
"You may be disappointed if you fail, but you are doomed if you don’t try",
"Failure will never overtake me if my determination to succeed is strong enough",
"It’s not whether you get knocked down, it’s whether you get up",
"It’s during our darkest moments that we must focus to see the light",
"Many of life’s failures are people who did not realize how close they were to success when they gave up",
"What you lack in talent can be made up with desire, hustle, and giving 110% all the time",
"Don’t let what you cannot do interfere with what you can do",
"Nothing is impossible, the world itself says, ‘I’m possible!’",
"The question isn’t who is going to let me; it’s who is going to stop me?",
"Winning isn’t everything, but wanting to win is",
"It does not matter how slowly you go as long as you do not stop",
"The two most important days in your life are the day you are born and the day you find out why",
"When you stop chasing the wrong things, you give the right things a chance to catch you",
"Decide upon your major definite purpose in life and then organize all your activities around it",
"It is never too late to be what you might have been",
"The man who has confidence in himself gains the confidence of others",
"Try not to become a person of success, but rather, try to become a person of value",
"If you cannot do great things, do small things in a great way",
"Go the extra mile today",
"Don’t judge each day by the harvest you reap but by the seeds that you plant",
"Keep your face always toward the sunshine and shadows will fall behind you",
"When you reach the end of your rope, tie a knot in it and hang on",
"Give up",
"Don't believe in yourself. Believe in me, who believes in you",
"Bite off more than you can chew. Then chew it",
"Better dead than a red",
"You have no limits",
"Even if you fall on your face, you're still moving forward",
"If you never give up, you never lose",
"Better to die on your feet than live on your knees",
"We need your help, Star Fox!",
"Do a barrel roll! (Z or R)",
"Never give up. Trust your instincts",
"Star Fox, I want you to take out the enemy bioweapon!",
"Don't let them get to the supply depot!"]

inspiration = ["The only limit to our realization of tomorrow will be our doubts of today",
"Don’t be afraid to give up the good for the great",
"The secret of getting ahead is getting started",
"The only impossible journey is the one you never begin",
"The best way to get started is to quit talking and begin doing",
"When you know what you want, and want it bad enough, you’ll find a way to get it",
"Never let the fear of striking out keep you from playing the game",
"If you genuinely want something, don’t wait for it"
"The most difficult thing is the decision to act; the rest is merely tenacity",
"You don’t have to be great to start, but you have to start to be great",
"You miss 100% of the shots you don’t take",
"Everything you’ve ever wanted is on the other side of fear",
"I believe that the only courage anybody ever needs is the courage to follow your dreams",
"Whatever the mind of man can conceive and believe, it can achieve",
"Whether you think you can or think you can’t, you’re right",
"Magic is believing in yourself; if you can do that, you can make anything happen",
"Believe you can, and you’re halfway there",
"There are no limits to what you can accomplish, except the limits you place on your own thinking",
"All our dreams will come true if we have the courage to pursue them",
"Too many of us are not living our dreams because we are living our fears",
"I have learned over the years that when one’s mind is made up, this diminishes fear",
"Believe you can, and you’re halfway there",
"In this moment, I am euphoric. Not because of any phony god's blessing. But because, I am enlightened by my intelligence",
"All our dreams will come true, if we have the courage to pursue them",
"The secret of change is to focus all of your energy, not on fighting the old, but on building the new",
"A bad attitude is like a flat tire; if you don’t change it, you won’t go anywhere",
"The future belongs to those who believe in the beauty of their dreams",
"Dream big and dare to fail",
"Setting goals is the first step in turning the invisible into the visible",
"Imagine your life is perfect in every respect; what would it look like?",
"I think goals should never be easy; they should force you to work, even if they are uncomfortable at the time",
"People who are crazy enough to think they can change the world are the ones who do",
"Whatever the mind can conceive and believe, it can achieve",
"If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success",
"You are never too old to set another goal or to dream a new dream",
"Dreaming, after all, is a form of planning",
"Always bear in mind that your own resolution to success is more important than any other one thing",
"I find that the harder I work, the more luck I seem to have",
"I never dreamed about success; I worked for it",
"For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded",
"Success is walking from failure to failure with no loss of enthusiasm",
"I attribute my success to this: I never gave or took any excuse",
"Success usually comes to those who are too busy to be looking for it",
"Today’s accomplishments were yesterday’s impossibilities",
"If you look really closely, most overnight successes took a long time",
"When you want to succeed as bad as you want to breathe, then you’ll be successful",
"Things work out the best for those who make the best of how things work out",
"You suck",
"Success is a personal standard, reaching for the highest that is in us, becoming all we can be",
"The road to success and the road to failure are almost exactly the same",
"Success is not final; failure is not fatal: it is the courage to continue that counts",
"Our greatest glory is not in never falling, but in rising every time we fall",
"You will face many defeats in life, but never let yourself be defeated",
"You may be disappointed if you fail, but you are doomed if you don’t try",
"Failure will never overtake me if my determination to succeed is strong enough",
"It’s not whether you get knocked down, it’s whether you get up",
"It’s during our darkest moments that we must focus to see the light",
"Many of life’s failures are people who did not realize how close they were to success when they gave up",
"Don’t let what you cannot do interfere with what you can do",
"Nothing is impossible, the world itself says, ‘I’m possible!’",
"The question isn’t who is going to let me; it’s who is going to stop me?",
"Winning isn’t everything, but wanting to win is",
"It does not matter how slowly you go as long as you do not stop",
"The two most important days in your life are the day you are born and the day you find out why",
"When you stop chasing the wrong things, you give the right things a chance to catch you",
"Decide upon your major definite purpose in life and then organize all your activities around it",
"It is never too late to be what you might have been",
"The man who has confidence in himself gains the confidence of others",
"Try not to become a person of success, but rather, try to become a person of value",
"If you cannot do great things, do small things in a great way",
"Go the extra mile today",
"Don’t judge each day by the harvest you reap but by the seeds that you plant",
"Keep your face always toward the sunshine and shadows will fall behind you",
"When you reach the end of your rope, tie a knot in it and hang on",
"Give up!",
"Don't believe in yourself. Believe in me, who believes in you",
"Bite off more than you can chew. Then chew it",
"Better dead than a red",
"You have no limits",
"Even if you fall on your face, you're still moving forward",
"If you never give up, you never lose",
"Better to die on your feet than live on your knees",
"Do a barrel roll! (Z or R)",
"Never give up. Trust your instincts",
"Star Fox, I want you to take out the enemy bioweapon!",
"Don't let them get to the supply depot!"]

import random
import os

def send_affirmation():
    try:
        affirmation = random.choice(inspiration)
        os.system(f"""osascript -e 'display notification "{affirmation}" with title "Daily Affirmation"'""")
    except Exception as e:
        print("Error sending notification:", e)

# Send an immediate notification
send_affirmation()
